name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Check TypeScript
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test

      - name: Build plugin
        run: npm run build

      - name: Check build artifacts
        run: |
          if [ ! -f "main.js" ]; then
            echo "❌ main.js not found after build"
            exit 1
          fi
          if [ ! -f "styles/main.css" ]; then
            echo "❌ styles/main.css not found"
            exit 1
          fi
          echo "✅ Build artifacts verified"
